name: Org Members Full Activity Log

on:
  workflow_dispatch:   # Manual trigger

jobs:
  get-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Org Members Activity Logs
        run: |
          ORG="0deployment"
          TOKEN="${{ secrets.GH_AC }}"
          OUTPUT="members_activity.csv"

          echo "username,event_type,repo,created_at" > $OUTPUT

          # Get all members of the org
          MEMBERS=$(curl -s -H "Authorization: Bearer $TOKEN" \
            "https://api.github.com/orgs/$ORG/members?per_page=100" | jq -r '.[].login')

          for USER in $MEMBERS; do
            PAGE=1
            while true; do
              EVENTS=$(curl -s -H "Authorization: Bearer $TOKEN" \
                "https://api.github.com/users/$USER/events?per_page=100&page=$PAGE")

              COUNT=$(echo "$EVENTS" | jq length)

              if [ "$COUNT" -eq 0 ]; then
                break
              fi

              echo "$EVENTS" | jq -r \
                '.[] | [.actor.login, .type, .repo.name, .created_at] | @csv' >> $OUTPUT

              PAGE=$((PAGE+1))
            done
          done

          echo "Generated activity log at $OUTPUT"
          head -n 20 $OUTPUT  # show preview

      - name: Install Python and Pandas
        run: |
          python3 -m pip install --upgrade pip
          pip install pandas

      - name: Generate Last Activity per User
        run: |
          python3 << 'EOF'
          import pandas as pd

          # Load full log
          df = pd.read_csv("members_activity.csv")

          # Convert created_at to datetime
          df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')

          # Sort and get latest per user
          last_activity = df.sort_values('created_at').groupby('username').tail(1)

          # Save result
          last_activity.to_csv("last_activity.csv", index=False)

          print("✅ Last activity per user saved to last_activity.csv")
          print(last_activity)
          EOF

      - name: Upload CSVs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: org-members-activity
          path: |
            members_activity.csv
            last_activity.csv
