name: Org Members Last Activity

on:
  workflow_dispatch:   # Manual trigger

jobs:
  get-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Org Members Last Activity
        run: |
          ORG="0deployment"
          TOKEN="${{ secrets.GH_AC }}"
          OUTPUT="last_usage.csv"

          echo "username,event_type,repo,created_at" > $OUTPUT

          # Get all members of the org
          MEMBERS=$(curl -s -H "Authorization: Bearer $TOKEN" \
            "https://api.github.com/orgs/$ORG/members?per_page=100" | jq -r '.[].login')

          for USER in $MEMBERS; do
            EVENT=$(curl -s -H "Authorization: Bearer $TOKEN" \
              "https://api.github.com/users/$USER/events?per_page=1" )

            if [ "$(echo "$EVENT" | jq length)" -gt 0 ]; then
              echo "$EVENT" | jq -r \
                --arg user "$USER" \
                '.[] | [$user, .type, .repo.name, .created_at] | @csv' >> $OUTPUT
            else
              echo "$USER,no_activity,no_repo,no_date" >> $OUTPUT
            fi
          done

          cat $OUTPUT

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: org-last-usage
          path: last_usage.csv
